services:

  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: hps
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/var/lib/postgresql/data

  hps-server:
    container_name: hps-server
    image: m04ph3u2/hps-server:latest
    restart: always
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:v2.8.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email heatpeakstudio@gmail.com -d heatpeakstudio.com -d www.heatpeakstudio.com --rsa-key-size 4096 --agree-tos --no-eff-email
    depends_on:
      - nginx